//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESQ_Server.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emergency_Events
    {
        public int id { get; set; }
        public int UserId { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Status { get; set; }
    
        public virtual user user { get; set; }
    }
}
