//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESQ_Server.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.Emergency_Events = new HashSet<Emergency_Events>();
        }
    
        public int id { get; set; }
        public string full_Name { get; set; }
        public string UserName { get; set; }
        public string Personal_PhoneNumber { get; set; }
        public string Emergency_PhoneNumber { get; set; }
        public string Region { get; set; }
        public string District { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emergency_Events> Emergency_Events { get; set; }
    }
}
