//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESQ_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role_id { get; set; }
        public string FullName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Branch { get; set; }
        public string AadharNumber { get; set; }
        public string UANNumber { get; set; }
        public string BloodGroup { get; set; }
        public string BankAccount_1 { get; set; }
        public string BankAccount_2 { get; set; }
        public string PhoneNumber { get; set; }
        public string Employee_Photo { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
